# Generated by Django 4.2.10 on 2026-04-12 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("customer_id", "product_id")},
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product_type",
        ),
    ]
