# Generated by Django 4.2.10 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_refactor_to_single_product_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="customer_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(fields=("session_key", "product_id"), name="unique_cart_session_product"),
        ),
    ]
