# Generated by Django 4.2.10 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_harden_cart_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price_snapshot",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
