# Generated by Django 4.2.10 on 2026-04-12 00:00

from django.db import migrations, models
from django.utils.text import slugify


def populate_product_slugs(apps, schema_editor):
    ProductModel = apps.get_model("catalog", "ProductModel")

    for product in ProductModel.objects.all().order_by("id"):
        base_slug = slugify(product.name) or "product"
        slug = base_slug
        suffix = 2

        while ProductModel.objects.exclude(pk=product.pk).filter(slug=slug).exists():
            slug = f"{base_slug}-{suffix}"
            suffix += 1

        product.slug = slug
        product.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_product_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
