PRODUCT_SEED = [
    {
        "name": "MacBook Pro 14",
        "slug": "macbook-pro-14",
        "short_description": "Laptop cao cap cho lap trinh va cong viec sang tao.",
        "description": "MacBook Pro 14 inch voi chip M3 Pro, RAM 16GB, SSD 512GB, man hinh Liquid Retina XDR phu hop lap trinh, thiet ke, video editing va cong viec chuyen nghiep.",
        "base_price": "2000.00",
        "stock": 10,
        "attributes": {"ram": "16GB", "cpu": "M3 Pro", "storage": "512GB SSD"},
        "tags": ["laptop", "apple", "developer", "premium"],
        "image_urls": ["https://example.com/images/macbook-pro-14.jpg"],
    },
    {
        "name": "Dell XPS 13",
        "slug": "dell-xps-13",
        "short_description": "Ultrabook gon nhe cho hoc tap va lam viec.",
        "description": "Dell XPS 13 voi Intel Core i7, RAM 16GB, SSD 512GB, thiet ke nhe, man hinh sac net, phu hop cho sinh vien va nhan vien van phong.",
        "base_price": "1450.00",
        "stock": 8,
        "attributes": {"ram": "16GB", "cpu": "Intel Core i7", "storage": "512GB SSD"},
        "tags": ["laptop", "dell", "ultrabook", "office"],
        "image_urls": ["https://example.com/images/dell-xps-13.jpg"],
    },
    {
        "name": "Logitech G Pro X Headset",
        "slug": "logitech-g-pro-x-headset",
        "short_description": "Tai nghe gaming tap trung vao voice chat va esports.",
        "description": "Tai nghe gaming Logitech G Pro X co micro chat ro, am thanh vong, dem tai mem, phu hop cho game thu can giao tiep va dinh huong tot.",
        "base_price": "129.00",
        "stock": 20,
        "attributes": {"connection": "3.5mm", "microphone": "Blue Voice", "type": "over-ear"},
        "tags": ["headset", "gaming", "logitech", "esports"],
        "image_urls": ["https://example.com/images/logitech-g-pro-x.jpg"],
    },
    {
        "name": "Nike Dri-FIT Training Shirt",
        "slug": "nike-dri-fit-training-shirt",
        "short_description": "Ao tap luyen thoa khi cho hoat dong hang ngay.",
        "description": "Ao Nike Dri-FIT co chat lieu hut am, nhanh kho, phu hop cho gym, chay bo va van dong hang ngay.",
        "base_price": "35.00",
        "stock": 30,
        "attributes": {"material": "polyester", "fit": "regular", "gender": "unisex"},
        "tags": ["clothes", "nike", "training", "sportswear"],
        "image_urls": ["https://example.com/images/nike-dri-fit-shirt.jpg"],
    },
    {
        "name": "Uniqlo Oxford Shirt",
        "slug": "uniqlo-oxford-shirt",
        "short_description": "Ao so mi co ban de mac di hoc, di lam, di choi.",
        "description": "Ao so mi Oxford cua Uniqlo co phom vua van, de phoi do, phu hop cho phong cach casual va smart casual.",
        "base_price": "29.00",
        "stock": 18,
        "attributes": {"material": "cotton", "fit": "regular", "style": "casual"},
        "tags": ["clothes", "uniqlo", "shirt", "casual"],
        "image_urls": ["https://example.com/images/uniqlo-oxford-shirt.jpg"],
    },
]
